name: ddr
channels:
  - conda-forge
dependencies:
  - awkward=2.8.1
  - black=25.1.0
  - coffea=2025.3.0
  - dask=2025.2.0
  - dask-awkward=2025.3.0
  - flake8=7.2.0
  - fsspec=2025.3.0
  - fsspec-xrootd=0.5.1
  - ndcctools=7.14.8
  - numpy=2.1.3
  - python=3.13.2
  - rich=13.9.4
  - uproot=5.6.0
